
ãroot"_tf_keras_model*Î{"name": "caps_net", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "must_restore_from_config": false, "class_name": "CapsNet", "config": {"layer was saved without config": true}, "is_graph_network": false, "full_save_spec": {"class_name": "__tuple__", "items": [[{"class_name": "__tuple__", "items": [{"class_name": "TypeSpec", "type_spec": "tf.TensorSpec", "serialized": [{"class_name": "TensorShape", "items": [null, 126, 18]}, "float32", "input_1"]}, {"class_name": "TypeSpec", "type_spec": "tf.TensorSpec", "serialized": [{"class_name": "TensorShape", "items": [null, 126, 126]}, "int32", "input_2"]}]}], {}]}, "save_spec": {"class_name": "__tuple__", "items": [{"class_name": "TypeSpec", "type_spec": "tf.TensorSpec", "serialized": [{"class_name": "TensorShape", "items": [null, 126, 18]}, "float32", "input_1"]}, {"class_name": "TypeSpec", "type_spec": "tf.TensorSpec", "serialized": [{"class_name": "TensorShape", "items": [null, 126, 126]}, "int32", "input_2"]}]}, "keras_version": "2.7.0", "backend": "tensorflow", "model_config": {"class_name": "CapsNet"}, "training_config": {"loss": "categorical_crossentropy", "metrics": [[{"class_name": "MeanMetricWrapper", "config": {"name": "accuracy", "dtype": "float32", "fn": "categorical_accuracy"}, "shared_object_id": 0}, {"class_name": "MeanMetricWrapper", "config": {"name": "mse", "dtype": "float32", "fn": "mean_squared_error"}, "shared_object_id": 1}, {"class_name": "MeanMetricWrapper", "config": {"name": "categorical_crossentropy", "dtype": "float32", "fn": "categorical_crossentropy"}, "shared_object_id": 2}]], "weighted_metrics": null, "loss_weights": null, "optimizer_config": {"class_name": "Adam", "config": {"name": "Adam", "learning_rate": 0.00039999998989515007, "decay": 0.0, "beta_1": 0.8999999761581421, "beta_2": 0.9990000128746033, "epsilon": 1e-07, "amsgrad": false}}}}2
Ãroot.graphconv1"_tf_keras_layer*ü{"name": "graph_convolution_layer", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "GraphConvolutionLayer", "config": {"layer was saved without config": true}, "build_input_shape": [{"class_name": "TensorShape", "items": [null, 126, 18]}, {"class_name": "TensorShape", "items": [null, 126, 126]}]}2
Õroot.graphconv2"_tf_keras_layer*†{"name": "graph_convolution_layer_1", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "GraphConvolutionLayer", "config": {"layer was saved without config": true}, "build_input_shape": [{"class_name": "TensorShape", "items": [null, 126, 8]}, {"class_name": "TensorShape", "items": [null, 126, 126]}]}2
Õroot.graphconv3"_tf_keras_layer*†{"name": "graph_convolution_layer_2", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "GraphConvolutionLayer", "config": {"layer was saved without config": true}, "build_input_shape": [{"class_name": "TensorShape", "items": [null, 126, 8]}, {"class_name": "TensorShape", "items": [null, 126, 126]}]}2
Õroot.graphconv4"_tf_keras_layer*†{"name": "graph_convolution_layer_3", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "GraphConvolutionLayer", "config": {"layer was saved without config": true}, "build_input_shape": [{"class_name": "TensorShape", "items": [null, 126, 8]}, {"class_name": "TensorShape", "items": [null, 126, 126]}]}2
 
root.stack"_tf_keras_layer*¢{"name": "stack_layer", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "StackLayer", "config": {"name": "stack_layer", "trainable": true, "dtype": "float32"}, "shared_object_id": 3, "build_input_shape": [{"class_name": "TensorShape", "items": [null, 126, 8]}, {"class_name": "TensorShape", "items": [null, 126, 8]}, {"class_name": "TensorShape", "items": [null, 126, 8]}, {"class_name": "TensorShape", "items": [null, 126, 8]}]}2
±
root.caps1"_tf_keras_layer*â{"name": "capsule_layer", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "CapsuleLayer", "config": {"layer was saved without config": true}, "build_input_shape": [{"class_name": "TensorShape", "items": [null, 126]}, {"class_name": "TensorShape", "items": [null, 126, 8, 4]}]}2
±
root.caps2"_tf_keras_layer*â{"name": "capsule_layer_1", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "CapsuleLayer", "config": {"layer was saved without config": true}, "build_input_shape": [{"class_name": "TensorShape", "items": [null, 20]}, {"class_name": "TensorShape", "items": [null, 20, 4, 4]}]}2
±
root.caps3"_tf_keras_layer*â{"name": "capsule_layer_2", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "CapsuleLayer", "config": {"layer was saved without config": true}, "build_input_shape": [{"class_name": "TensorShape", "items": [null, 12]}, {"class_name": "TensorShape", "items": [null, 12, 4, 6]}]}2
∏nroot.keras_api.metrics.0"_tf_keras_metric*Å{"class_name": "Mean", "name": "loss", "dtype": "float32", "config": {"name": "loss", "dtype": "float32"}, "shared_object_id": 4}2
Îoroot.keras_api.metrics.1"_tf_keras_metric*¥{"class_name": "MeanMetricWrapper", "name": "accuracy", "dtype": "float32", "config": {"name": "accuracy", "dtype": "float32", "fn": "categorical_accuracy"}, "shared_object_id": 0}2
ﬂproot.keras_api.metrics.2"_tf_keras_metric*®{"class_name": "MeanMetricWrapper", "name": "mse", "dtype": "float32", "config": {"name": "mse", "dtype": "float32", "fn": "mean_squared_error"}, "shared_object_id": 1}2
èqroot.keras_api.metrics.3"_tf_keras_metric*ÿ{"class_name": "MeanMetricWrapper", "name": "categorical_crossentropy", "dtype": "float32", "config": {"name": "categorical_crossentropy", "dtype": "float32", "fn": "categorical_crossentropy"}, "shared_object_id": 2}2