
èroot"_tf_keras_model*Ô{"name": "caps_net_b", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "must_restore_from_config": false, "class_name": "CapsNetB", "config": {"layer was saved without config": true}, "is_graph_network": false, "full_save_spec": {"class_name": "__tuple__", "items": [[{"class_name": "__tuple__", "items": [{"class_name": "TypeSpec", "type_spec": "tf.TensorSpec", "serialized": [{"class_name": "TensorShape", "items": [null, 126, 18]}, "float32", "input_1"]}, {"class_name": "TypeSpec", "type_spec": "tf.TensorSpec", "serialized": [{"class_name": "TensorShape", "items": [null, 126, 126]}, "int32", "input_2"]}]}], {}]}, "save_spec": {"class_name": "__tuple__", "items": [{"class_name": "TypeSpec", "type_spec": "tf.TensorSpec", "serialized": [{"class_name": "TensorShape", "items": [null, 126, 18]}, "float32", "input_1"]}, {"class_name": "TypeSpec", "type_spec": "tf.TensorSpec", "serialized": [{"class_name": "TensorShape", "items": [null, 126, 126]}, "int32", "input_2"]}]}, "keras_version": "2.7.0", "backend": "tensorflow", "model_config": {"class_name": "CapsNetB"}, "training_config": {"loss": "categorical_crossentropy", "metrics": [[{"class_name": "MeanMetricWrapper", "config": {"name": "accuracy", "dtype": "float32", "fn": "categorical_accuracy"}, "shared_object_id": 0}, {"class_name": "MeanMetricWrapper", "config": {"name": "mse", "dtype": "float32", "fn": "mean_squared_error"}, "shared_object_id": 1}, {"class_name": "MeanMetricWrapper", "config": {"name": "categorical_crossentropy", "dtype": "float32", "fn": "categorical_crossentropy"}, "shared_object_id": 2}]], "weighted_metrics": null, "loss_weights": null, "optimizer_config": {"class_name": "Adam", "config": {"name": "Adam", "learning_rate": 0.00039999998989515007, "decay": 0.0, "beta_1": 0.8999999761581421, "beta_2": 0.9990000128746033, "epsilon": 1e-07, "amsgrad": false}}}}2
Ãroot.graphconv1"_tf_keras_layer*ü{"name": "graph_convolution_layer", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "GraphConvolutionLayer", "config": {"layer was saved without config": true}, "build_input_shape": [{"class_name": "TensorShape", "items": [null, 126, 18]}, {"class_name": "TensorShape", "items": [null, 126, 126]}]}2
Õroot.graphconv2"_tf_keras_layer*†{"name": "graph_convolution_layer_1", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "GraphConvolutionLayer", "config": {"layer was saved without config": true}, "build_input_shape": [{"class_name": "TensorShape", "items": [null, 126, 8]}, {"class_name": "TensorShape", "items": [null, 126, 126]}]}2
Õroot.graphconv3"_tf_keras_layer*†{"name": "graph_convolution_layer_2", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "GraphConvolutionLayer", "config": {"layer was saved without config": true}, "build_input_shape": [{"class_name": "TensorShape", "items": [null, 126, 8]}, {"class_name": "TensorShape", "items": [null, 126, 126]}]}2
Õroot.graphconv4"_tf_keras_layer*†{"name": "graph_convolution_layer_3", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "GraphConvolutionLayer", "config": {"layer was saved without config": true}, "build_input_shape": [{"class_name": "TensorShape", "items": [null, 126, 8]}, {"class_name": "TensorShape", "items": [null, 126, 126]}]}2
 
root.stack"_tf_keras_layer*¢{"name": "stack_layer", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "StackLayer", "config": {"name": "stack_layer", "trainable": true, "dtype": "float32"}, "shared_object_id": 3, "build_input_shape": [{"class_name": "TensorShape", "items": [null, 126, 8]}, {"class_name": "TensorShape", "items": [null, 126, 8]}, {"class_name": "TensorShape", "items": [null, 126, 8]}, {"class_name": "TensorShape", "items": [null, 126, 8]}]}2
±
root.caps1"_tf_keras_layer*â{"name": "capsule_layer", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "CapsuleLayer", "config": {"layer was saved without config": true}, "build_input_shape": [{"class_name": "TensorShape", "items": [null, 126]}, {"class_name": "TensorShape", "items": [null, 126, 8, 4]}]}2
±
root.caps2"_tf_keras_layer*â{"name": "capsule_layer_1", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "CapsuleLayer", "config": {"layer was saved without config": true}, "build_input_shape": [{"class_name": "TensorShape", "items": [null, 20]}, {"class_name": "TensorShape", "items": [null, 20, 4, 4]}]}2
±
root.caps3"_tf_keras_layer*â{"name": "capsule_layer_2", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "CapsuleLayer", "config": {"layer was saved without config": true}, "build_input_shape": [{"class_name": "TensorShape", "items": [null, 12]}, {"class_name": "TensorShape", "items": [null, 12, 4, 6]}]}2
¨	
root.caps4"_tf_keras_layer*Ñ{"name": "capsule_layer_3", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "CapsuleLayer", "config": {"layer was saved without config": true}}2
ë
root.flatten"_tf_keras_layer*Á{"name": "flatten", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Flatten", "config": {"name": "flatten", "trainable": true, "dtype": "float32", "data_format": "channels_last"}, "shared_object_id": 4, "input_spec": {"class_name": "InputSpec", "config": {"dtype": null, "shape": null, "ndim": null, "max_ndim": null, "min_ndim": 1, "axes": {}}, "shared_object_id": 5}}2
π	root.dense1"_tf_keras_layer*ê	{"name": "dense", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dense", "config": {"name": "dense", "trainable": true, "dtype": "float32", "units": 20, "activation": {"class_name": "LeakyReLU", "config": {"name": "leaky_re_lu", "trainable": true, "dtype": "float32", "alpha": 0.30000001192092896}, "shared_object_id": 6}, "use_bias": true, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null}, "shared_object_id": 7}, "bias_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 8}, "kernel_regularizer": {"class_name": "L1L2", "config": {"l1": 4.999999873689376e-06, "l2": 4.999999873689376e-06}, "shared_object_id": 9}, "bias_regularizer": null, "activity_regularizer": null, "kernel_constraint": null, "bias_constraint": null}, "shared_object_id": 10, "input_spec": {"class_name": "InputSpec", "config": {"dtype": null, "shape": null, "ndim": null, "max_ndim": null, "min_ndim": 2, "axes": {"-1": 288}}, "shared_object_id": 11}, "build_input_shape": {"class_name": "TensorShape", "items": [null, 288]}}2
´root.dense2"_tf_keras_layer*Ç{"name": "dense_1", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dense", "config": {"name": "dense_1", "trainable": true, "dtype": "float32", "units": 6, "activation": "linear", "use_bias": true, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null}, "shared_object_id": 12}, "bias_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 13}, "kernel_regularizer": {"class_name": "L1L2", "config": {"l1": 4.999999873689376e-06, "l2": 4.999999873689376e-06}, "shared_object_id": 14}, "bias_regularizer": null, "activity_regularizer": null, "kernel_constraint": null, "bias_constraint": null}, "shared_object_id": 15, "input_spec": {"class_name": "InputSpec", "config": {"dtype": null, "shape": null, "ndim": null, "max_ndim": null, "min_ndim": 2, "axes": {"-1": 20}}, "shared_object_id": 16}, "build_input_shape": {"class_name": "TensorShape", "items": [null, 20]}}2
◊root.softmax"_tf_keras_layer*≠{"name": "softmax", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Softmax", "config": {"name": "softmax", "trainable": true, "dtype": "float32", "axis": -1}, "shared_object_id": 17}2
¸Froot.dense1.activation"_tf_keras_layer*»{"name": "leaky_re_lu", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "LeakyReLU", "config": {"name": "leaky_re_lu", "trainable": true, "dtype": "float32", "alpha": 0.30000001192092896}, "shared_object_id": 6}2
∫°root.keras_api.metrics.0"_tf_keras_metric*Ç{"class_name": "Mean", "name": "loss", "dtype": "float32", "config": {"name": "loss", "dtype": "float32"}, "shared_object_id": 18}2
Ï¢root.keras_api.metrics.1"_tf_keras_metric*¥{"class_name": "MeanMetricWrapper", "name": "accuracy", "dtype": "float32", "config": {"name": "accuracy", "dtype": "float32", "fn": "categorical_accuracy"}, "shared_object_id": 0}2
‡£root.keras_api.metrics.2"_tf_keras_metric*®{"class_name": "MeanMetricWrapper", "name": "mse", "dtype": "float32", "config": {"name": "mse", "dtype": "float32", "fn": "mean_squared_error"}, "shared_object_id": 1}2
ê§root.keras_api.metrics.3"_tf_keras_metric*ÿ{"class_name": "MeanMetricWrapper", "name": "categorical_crossentropy", "dtype": "float32", "config": {"name": "categorical_crossentropy", "dtype": "float32", "fn": "categorical_crossentropy"}, "shared_object_id": 2}2